import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { AppointmentStatus, Prisma, Role, ServiceStatus, SpecialistStatus } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { AccessService } from '../../common/services/access.service';
import { RequestUser } from '../../common/types/request-user.type';
import { NotificationsService } from '../notifications/notifications.service';
import { CreateAppointmentDto, AppointmentQueryDto, UpdateAppointmentDto } from './dto/appointments.dto';

@Injectable()
export class AppointmentsService {
  constructor(private readonly prisma: PrismaService, private readonly access: AccessService, private readonly notifications: NotificationsService) {}
  async create(dto: CreateAppointmentDto, actorId: string) { const startAt = new Date(dto.startAt); const endAt = new Date(dto.endAt); this.assertRange(startAt, endAt); return this.prisma.$transaction(async (tx) => { await this.validateDependencies(dto.childId, dto.parentId, dto.specialistId, dto.serviceId, tx); await this.assertNoConflict(dto.specialistId, startAt, endAt, undefined, tx); const appointment = await tx.appointment.create({ data: { ...dto, startAt, endAt } }); const parent = await tx.parent.findUniqueOrThrow({ where: { id: dto.parentId }, select: { userId: true } }); await this.notifications.create({ userId: parent.userId, type: 'APPOINTMENT', title: 'Appointment scheduled', message: `An appointment is scheduled for ${startAt.toISOString()}.`, relatedEntity: 'Appointment', relatedEntityId: appointment.id, dedupeKey: `appointment-created:${appointment.id}`, allowSms: true }, tx); await tx.activityLog.create({ data: { userId: actorId, action: 'APPOINTMENT_CREATED', entity: 'Appointment', entityId: appointment.id, description: 'Created appointment' } }); await tx.outboxEvent.create({ data: { eventType: 'APPOINTMENT_CREATED', aggregateType: 'Appointment', aggregateId: appointment.id, payload: { appointmentId: appointment.id } } }); return appointment; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
  async list(query: AppointmentQueryDto, user: RequestUser) { const where: Prisma.AppointmentWhereInput = { childId: query.childId, specialistId: query.specialistId, status: query.status }; if (user.role === Role.PARENT) where.parent = { userId: user.id }; if (user.role === Role.SPECIALIST) where.specialist = { userId: user.id }; const [items, total] = await this.prisma.$transaction([this.prisma.appointment.findMany({ where, include: { child: true, service: true, specialist: { include: { user: { select: { fullName: true } } } } }, orderBy: { startAt: 'asc' }, skip: (query.page - 1) * query.limit, take: query.limit }), this.prisma.appointment.count({ where })]); return { items, meta: { page: query.page, limit: query.limit, total } }; }
  async get(id: string, user: RequestUser) { const appointment = await this.prisma.appointment.findUnique({ where: { id }, include: { child: true, service: true, specialist: { include: { user: { select: { fullName: true } } } }, session: true, attendance: true } }); if (!appointment) throw new NotFoundException('Appointment not found'); await this.assertAppointmentAccess(appointment.id, user); return appointment; }
  async update(id: string, dto: UpdateAppointmentDto, actorId: string) { const existing = await this.prisma.appointment.findUnique({ where: { id } }); if (!existing) throw new NotFoundException('Appointment not found'); if (!([AppointmentStatus.SCHEDULED, AppointmentStatus.CONFIRMED] as AppointmentStatus[]).includes(existing.status)) throw new BadRequestException('Only scheduled or confirmed appointments can be changed'); const startAt = dto.startAt ? new Date(dto.startAt) : existing.startAt; const endAt = dto.endAt ? new Date(dto.endAt) : existing.endAt; this.assertRange(startAt, endAt); const specialistId = dto.specialistId ?? existing.specialistId; if (dto.specialistId) { const specialist = await this.prisma.specialist.findUnique({ where: { id: specialistId } }); if (!specialist || specialist.status !== SpecialistStatus.ACTIVE) throw new BadRequestException('Specialist must be active'); } if (dto.serviceId) { const service = await this.prisma.service.findUnique({ where: { id: dto.serviceId } }); if (!service || service.status !== ServiceStatus.ACTIVE) throw new BadRequestException('Service must be active'); } await this.assertNoConflict(specialistId, startAt, endAt, id); const item = await this.prisma.appointment.update({ where: { id }, data: { ...dto, startAt, endAt } }); await this.log(actorId, 'APPOINTMENT_UPDATED', id, 'Updated appointment'); return item; }
  async confirm(id: string, actorId: string) { return this.transition(id, [AppointmentStatus.SCHEDULED] as AppointmentStatus[], AppointmentStatus.CONFIRMED, actorId, 'APPOINTMENT_CONFIRMED'); }
  async start(id: string, user: RequestUser) { const appointment = await this.prisma.appointment.findUnique({ where: { id }, include: { service: true } }); if (!appointment) throw new NotFoundException('Appointment not found'); await this.assertAppointmentAccess(appointment.id, user, true); if (!([AppointmentStatus.SCHEDULED, AppointmentStatus.CONFIRMED] as AppointmentStatus[]).includes(appointment.status)) throw new BadRequestException('Appointment cannot be started from its current status'); try { return await this.prisma.$transaction(async (tx) => { const updated = await tx.appointment.update({ where: { id }, data: { status: AppointmentStatus.IN_PROGRESS } }); const session = await tx.session.create({ data: { appointmentId: id, childId: appointment.childId, specialistId: appointment.specialistId, serviceId: appointment.serviceId, servicePriceSnapshot: appointment.service.price, startedAt: new Date() } }); await tx.activityLog.create({ data: { userId: user.id, action: 'SESSION_STARTED', entity: 'Session', entityId: session.id, description: 'Started session from appointment' } }); return { appointment: updated, session }; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch (error) { if (this.isUnique(error)) throw new ConflictException('Session is already started for this appointment'); throw error; } }
  async cancel(id: string, user: RequestUser) { const appointment = await this.prisma.appointment.findUnique({ where: { id } }); if (!appointment) throw new NotFoundException('Appointment not found'); await this.assertAppointmentAccess(id, user); return this.transition(id, [AppointmentStatus.SCHEDULED, AppointmentStatus.CONFIRMED] as AppointmentStatus[], AppointmentStatus.CANCELLED, user.id, 'APPOINTMENT_CANCELLED'); }
  async noShow(id: string, user: RequestUser) { const appointment = await this.prisma.appointment.findUnique({ where: { id } }); if (!appointment) throw new NotFoundException('Appointment not found'); await this.assertAppointmentAccess(id, user, true); return this.transition(id, [AppointmentStatus.SCHEDULED, AppointmentStatus.CONFIRMED] as AppointmentStatus[], AppointmentStatus.NO_SHOW, user.id, 'APPOINTMENT_NO_SHOW'); }
  private async validateDependencies(childId: string, parentId: string, specialistId: string, serviceId: string, tx: Prisma.TransactionClient) { const [child, relation, specialist, service] = await Promise.all([tx.child.findUnique({ where: { id: childId } }), tx.childParent.findUnique({ where: { childId_parentId: { childId, parentId } } }), tx.specialist.findUnique({ where: { id: specialistId } }), tx.service.findUnique({ where: { id: serviceId } })]); if (!child || child.status !== 'ACTIVE') throw new BadRequestException('Child must be active'); if (!relation) throw new BadRequestException('Parent must be related to child'); if (!specialist || specialist.status !== SpecialistStatus.ACTIVE) throw new BadRequestException('Specialist must be active'); if (!service || service.status !== ServiceStatus.ACTIVE) throw new BadRequestException('Service must be active'); }
  private async assertNoConflict(specialistId: string, startAt: Date, endAt: Date, excludeId?: string, tx: Prisma.TransactionClient = this.prisma) { const conflict = await tx.appointment.findFirst({ where: { specialistId, id: excludeId ? { not: excludeId } : undefined, status: { in: [AppointmentStatus.SCHEDULED, AppointmentStatus.CONFIRMED, AppointmentStatus.IN_PROGRESS] }, startAt: { lt: endAt }, endAt: { gt: startAt } }, select: { id: true } }); if (conflict) throw new ConflictException('Specialist has a conflicting appointment'); }
  private async assertAppointmentAccess(id: string, user: RequestUser, requireSpecialist = false) { const appointment = await this.prisma.appointment.findUnique({ where: { id }, select: { parent: { select: { userId: true } }, specialist: { select: { userId: true } } } }); if (!appointment) throw new NotFoundException('Appointment not found'); if (user.role === Role.SUPER_ADMIN || user.role === Role.ADMIN) return; if (user.role === Role.PARENT && !requireSpecialist && appointment.parent.userId === user.id) return; if (user.role === Role.SPECIALIST && appointment.specialist.userId === user.id) return; throw new ForbiddenException('You do not have access to this appointment'); }
  private async transition(id: string, from: AppointmentStatus[], to: AppointmentStatus, actorId: string, action: string) { const result = await this.prisma.appointment.updateMany({ where: { id, status: { in: from } }, data: { status: to } }); if (result.count !== 1) throw new BadRequestException('Invalid appointment state transition'); const item = await this.prisma.appointment.findUniqueOrThrow({ where: { id } }); await this.log(actorId, action, id, `Changed appointment status to ${to}`); return item; }
  private assertRange(startAt: Date, endAt: Date) { if (Number.isNaN(startAt.getTime()) || Number.isNaN(endAt.getTime()) || endAt <= startAt) throw new BadRequestException('endAt must be after startAt'); }
  private log(userId: string, action: string, entityId: string, description: string) { return this.prisma.activityLog.create({ data: { userId, action, entity: 'Appointment', entityId, description } }); }
  private isUnique(error: unknown): boolean { return typeof error === 'object' && error !== null && 'code' in error && error.code === 'P2002'; }
}
