import { AttendanceStatus, GoalStatus } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsDateString, IsEnum, IsInt, IsOptional, IsString, IsUUID, Length, Max, Min } from 'class-validator';
export class CreateAttendanceDto { @IsUUID() appointmentId!: string; @IsEnum(AttendanceStatus) status!: AttendanceStatus; @IsOptional() @IsString() @Length(1, 1000) note?: string; }
export class UpdateAttendanceDto { @IsEnum(AttendanceStatus) status!: AttendanceStatus; @IsOptional() @IsString() @Length(1, 1000) note?: string; }
export class CreateAssessmentDto { @IsUUID() childId!: string; @IsOptional() @IsUUID() specialistId?: string; @IsOptional() @IsString() @Max(3000) movement?: string; @IsOptional() @IsString() @Max(3000) coordination?: string; @IsOptional() @IsString() @Max(3000) flexibility?: string; @IsOptional() @IsString() @Max(3000) activityTolerance?: string; @IsOptional() @IsString() @Max(3000) sessionResponse?: string; @IsString() @Length(1, 5000) professionalObservation!: string; }
export class UpdateAssessmentDto { @IsOptional() @IsString() @Max(3000) movement?: string; @IsOptional() @IsString() @Max(3000) coordination?: string; @IsOptional() @IsString() @Max(3000) flexibility?: string; @IsOptional() @IsString() @Max(3000) activityTolerance?: string; @IsOptional() @IsString() @Max(3000) sessionResponse?: string; @IsOptional() @IsString() @Length(1, 5000) professionalObservation?: string; }
export class CreateProgressDto { @IsUUID() childId!: string; @IsOptional() @IsUUID() specialistId?: string; @IsString() @Length(1, 200) title!: string; @IsString() @Length(1, 5000) description!: string; }
export class UpdateProgressDto { @IsOptional() @IsString() @Length(1, 200) title?: string; @IsOptional() @IsString() @Length(1, 5000) description?: string; }
export class CreateGoalDto { @IsUUID() childId!: string; @IsOptional() @IsUUID() specialistId?: string; @IsString() @Length(1, 200) title!: string; @IsOptional() @IsString() @Max(5000) description?: string; @IsOptional() @IsDateString() targetDate?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(0) @Max(100) progress?: number; }
export class UpdateGoalDto { @IsOptional() @IsString() @Length(1, 200) title?: string; @IsOptional() @IsString() @Max(5000) description?: string; @IsOptional() @IsDateString() targetDate?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(0) @Max(100) progress?: number; @IsOptional() @IsEnum(GoalStatus) status?: GoalStatus; }
