import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { AccessService } from '../../common/services/access.service';
import { RequestUser } from '../../common/types/request-user.type';
import { CreateDocumentDto, RecordConsentDto, UpdateConsentDto, UpdateSettingsDto } from './dto/platform.dto';
@Injectable()
export class PlatformService {
  private readonly allowedMimeTypes = new Set(['application/pdf', 'image/jpeg', 'image/png']);
  constructor(private readonly prisma: PrismaService, private readonly access: AccessService) {}
  async consents(childId: string, user: RequestUser) { await this.access.assertChildAccess(user, childId); return this.prisma.consent.findMany({ where: { childId }, include: { parent: { include: { user: { select: { fullName: true } } } } } }); }
  async recordConsent(childId: string, dto: RecordConsentDto, user: RequestUser) { const parentId = dto.parentId ?? await this.access.currentParentId(user.id); if (dto.parentId && user.role === 'PARENT' && parentId !== await this.access.currentParentId(user.id)) throw new ForbiddenException('Parents may only record their own consent'); await this.access.assertParentOwnsChild(parentId, childId); return this.prisma.$transaction(async (tx) => { const consent = await tx.consent.upsert({ where: { childId_parentId_type: { childId, parentId, type: dto.type } }, create: { childId, parentId, type: dto.type, granted: dto.granted, grantedAt: dto.granted ? new Date() : null }, update: { granted: dto.granted, grantedAt: dto.granted ? new Date() : null } }); await tx.activityLog.create({ data: { userId: user.id, action: 'CONSENT_RECORDED', entity: 'Consent', entityId: consent.id, description: `${dto.type} consent ${dto.granted ? 'granted' : 'withdrawn'}` } }); return consent; }); }
  async updateConsent(id: string, dto: UpdateConsentDto, user: RequestUser) { const consent = await this.prisma.consent.findUnique({ where: { id } }); if (!consent) throw new NotFoundException('Consent not found'); if (user.role === 'PARENT' && consent.parentId !== await this.access.currentParentId(user.id)) throw new ForbiddenException('Parents may only change their own consent'); return this.prisma.$transaction(async (tx) => { const updated = await tx.consent.update({ where: { id }, data: { granted: dto.granted, grantedAt: dto.granted ? new Date() : null } }); await tx.activityLog.create({ data: { userId: user.id, action: 'CONSENT_UPDATED', entity: 'Consent', entityId: id, description: `Consent ${dto.granted ? 'granted' : 'withdrawn'}` } }); return updated; }); }
  async documents(childId: string, user: RequestUser) { await this.access.assertChildAccess(user, childId); return this.prisma.document.findMany({ where: { childId }, select: { id: true, name: true, mimeType: true, size: true, type: true, createdAt: true, parentId: true } }); }
  async registerDocument(childId: string, dto: CreateDocumentDto, user: RequestUser) { await this.access.assertChildAccess(user, childId); if (user.role === 'PARENT') { const parentId = await this.access.currentParentId(user.id); if (dto.parentId && dto.parentId !== parentId) throw new ForbiddenException('Parents may only attach their own documents'); await this.access.assertParentOwnsChild(parentId, childId); dto.parentId = parentId; } if (!this.allowedMimeTypes.has(dto.mimeType)) throw new BadRequestException('Unsupported document MIME type'); return this.prisma.$transaction(async (tx) => { const doc = await tx.document.create({ data: { ...dto, childId } }); await tx.activityLog.create({ data: { userId: user.id, action: 'DOCUMENT_REGISTERED', entity: 'Document', entityId: doc.id, description: `Registered private ${doc.type} document` } }); return { id: doc.id, name: doc.name, mimeType: doc.mimeType, size: doc.size, type: doc.type, createdAt: doc.createdAt }; }); }
  async document(id: string, user: RequestUser) { const doc = await this.prisma.document.findUnique({ where: { id } }); if (!doc) throw new NotFoundException('Document not found'); await this.access.assertChildAccess(user, doc.childId); return { id: doc.id, name: doc.name, fileKey: doc.fileKey, mimeType: doc.mimeType, size: doc.size, type: doc.type, createdAt: doc.createdAt }; }
  async getSettings() { const settings = await this.prisma.centerSettings.findFirst({ orderBy: { createdAt: 'asc' } }); return settings ?? { centerName: null, currency: 'UZS', timezone: 'Asia/Tashkent' }; }
  async updateSettings(dto: UpdateSettingsDto, userId: string) { const existing = await this.prisma.centerSettings.findFirst({ orderBy: { createdAt: 'asc' } }); const data = { ...dto, workingHours: dto.workingHours as Prisma.InputJsonValue | undefined, notificationSettings: dto.notificationSettings as Prisma.InputJsonValue | undefined }; const settings = existing ? await this.prisma.centerSettings.update({ where: { id: existing.id }, data }) : await this.prisma.centerSettings.create({ data: { centerName: dto.centerName ?? 'Rehabilitation Center', ...data } }); await this.prisma.activityLog.create({ data: { userId, action: 'SETTINGS_UPDATED', entity: 'CenterSettings', entityId: settings.id, description: 'Updated center settings' } }); return settings; }
  activityLogs(page: number, limit: number) { return this.prisma.activityLog.findMany({ orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit, include: { user: { select: { fullName: true, role: true } } } }); }
}
