import { Body, Controller, Get, Param, Patch, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { Role } from '@prisma/client';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { Roles } from '../../common/decorators/roles.decorator';
import { RequestUser } from '../../common/types/request-user.type';
import { CreateDocumentDto, RecordConsentDto, UpdateConsentDto, UpdateSettingsDto } from './dto/platform.dto';
import { PlatformService } from './platform.service';
@ApiTags('platform') @ApiBearerAuth() @Controller() export class PlatformController { constructor(private readonly platform: PlatformService) {} @Get('children/:childId/consents') consents(@Param('childId') id: string, @CurrentUser() user: RequestUser) { return this.platform.consents(id, user); } @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.PARENT) @Post('children/:childId/consents') consent(@Param('childId') id: string, @Body() dto: RecordConsentDto, @CurrentUser() user: RequestUser) { return this.platform.recordConsent(id, dto, user); } @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.PARENT) @Patch('consents/:id') updateConsent(@Param('id') id: string, @Body() dto: UpdateConsentDto, @CurrentUser() user: RequestUser) { return this.platform.updateConsent(id, dto, user); } @Get('children/:childId/documents') documents(@Param('childId') id: string, @CurrentUser() user: RequestUser) { return this.platform.documents(id, user); } @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.PARENT) @Post('children/:childId/documents') addDocument(@Param('childId') id: string, @Body() dto: CreateDocumentDto, @CurrentUser() user: RequestUser) { return this.platform.registerDocument(id, dto, user); } @Get('documents/:id') document(@Param('id') id: string, @CurrentUser() user: RequestUser) { return this.platform.document(id, user); } @Roles(Role.SUPER_ADMIN, Role.ADMIN) @Get('settings') settings() { return this.platform.getSettings(); } @Roles(Role.SUPER_ADMIN, Role.ADMIN) @Patch('settings') updateSettings(@Body() dto: UpdateSettingsDto, @CurrentUser() user: RequestUser) { return this.platform.updateSettings(dto, user.id); } @Roles(Role.SUPER_ADMIN, Role.ADMIN) @Get('activity-logs') logs(@Query('page') page = 1, @Query('limit') limit = 20) { return this.platform.activityLogs(Number(page), Math.min(100, Number(limit))); } }
